### PR TITLE
Add Things In Squares

### PR DESCRIPTION
**Pull request by lauripiisang**
A comic about things (in squares) and,
occasionally, rabbits.
http://www.thingsinsquares.com

### CODE REVIEW

**Comment by lauripiisang** [comment]
haven't tested this.

**Comment by lauripiisang** [comment]
P.S. The bonus panel is left out deliberately, clicking on the comic will get you to the page where you can see it, if you're interested. This ensures support for the artist & less waste for those who aren't interested.

**Comment by glensc** [comment]
afaik the framework (here) does not support adding extra text to indicate bonus or not

**Comment by lauripiisang** [comment]
"bonus or not" is indicated by the image itself.

**Pull request merged**
