### PR TITLE
Add turnoff.us plugin

### PR DESCRIPTION
**Pull request by Kasparsu**
Adds plugin for [turnoff.us](http://turnoff.us) webcomic

### CODE REVIEW

**Comment by Kasparsu** [comment]
hmm there seems to be additional content to be had. not sure how to add functionality to handle http://turnoff.us/geek/python-robots/ type comics where there is extra image.

**Comment by glensc** [comment]
bonus ok to be left out, same reason as here: https://github.com/glensc/comics-mailer/pull/11#issuecomment-259357392

**Comment by glensc** [comment]
seems working

```
http_request: http://turnoff.us/feed.xml...
http_request: http://turnoff.us/geek/commitland...
add: url = http://turnoff.us/image/en/commitland.png; desc = Commitland!, link = http://turnoff.us/geek/commitland
```

**Comment by Kasparsu** [comment]
Bonus could be used but not add as attachment but use original url? offline reading is out but mostly you read these online anyway.

**Pull request merged**
